### ISSUE TITLE
Click on (tray) notification  on linux not working properly.

### ISSUE THREAD

**Issue by darkstone** [hankbao/electron-notify#21]
I have 2 apps installed based on electron. Clicking on the notification opens both apps present. For example clicking on mailspring notification, also opens up telegram, and visa versa. 

My OS is ubuntu 17.10. It seems this is linux issue. 

Steps to reproduce: 

1. Install & configure [mailspring](https://getmailspring.com/)
1. Install [telegram](https://desktop.telegram.org/)
1. Send mail to mailbox.

**_Bug_**: 

Telegrams also opens.

**Comment by hankbao** [comment]
I suppose that neither telegram nor mailspring is using this module. So reporting your issue here wouldn't help anyway.

Btw, I guess your problem may be related to Electron itself or libappindactor it uses.

**Comment by darkstone** [comment]
Thanx for the quick reply. Realy appreciate it.
