### ISSUE TITLE
top-level import throws error

### ISSUE THREAD

**Issue by black-snow** [hankbao/electron-notify#4]
Having 

``` javascript
import notif from 'electron-notify'
// or
const whatever = require('electron-notify')
```

throws `Error: Cannot initialize "screen" module before app is ready.`

I "fixed" this by importing it on app.ready but it should be mentioned in the README.

> electron-prebuilt 1.0+
> Win7 /64

**Comment by sashazxtt** [comment]
@black-snow - did you require it inside the on ready event code?

**Comment by black-snow** [comment]
Did you read the original post?

**Comment by sashazxtt** [comment]
@black-snow 
yes i did. you said 'importing'.  import, as far as i know doesn't work anywhere but at the top of a source file. So, i'm not quite sure how you can 'import' in an app.ready event.

in my code i use 'require' in an app.ready event, indeed.

thanks for your time.

**Comment by wookoouk** [comment]
I have the exact same issue and some solution (app.ready)

**Comment by wookoouk** [comment]
Has this been resolved? I thought that the error was that the import/require should be at the top of the code but it does not work correctly (thus having to put it in the app.ready).

**Comment by wookoouk** [comment]
I am going to check if wrapping `electron-notifys` `setupConfig()` in `on('ready')` will solve the issue.

**Comment by black-snow** [comment]
I don't think it's been resolved. I just don't use this package anymore - I've switched to native notifications.

**Comment by wookoouk** [comment]
I switched from doing that to using this ;) (just because I dont like using `remote` and `ipcRenderer`.

**Comment by black-snow** [comment]
You could write a wrapper to hide most of the ipc stuff ;)

I have a browser window for notifications only that listens on an ipc event, hooks into click close events etc. and pushes an ipc event back for those. You have to set ip up once but *imho* it's pretty easy then.

**Comment by wookoouk** [comment]
Can a notification be issued if there is no window (just tray app)?

**Comment by black-snow** [comment]
Nope, you'll have to open a windowless `BrowserWindow`.

I could share my implementation if I find some time for that.
